# Generated by Django 6.0.8 on 2026-08-08 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_operation_id', models.UUIDField()),
                ('client_instance_id', models.CharField(blank=True, max_length=120)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_client_id', models.CharField(max_length=120)),
                ('operation_type', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('complete', 'Concluir'), ('cancel', 'Cancelar')], max_length=16)),
                ('payload_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('conflict', 'Conflito'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'client_operation_id'], name='core_sync_user_client_idx'), models.Index(fields=['status', 'created_at'], name='core_sync_status_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_operation_id'), name='core_sync_operation_user_client_id_unique'), models.CheckConstraint(condition=models.Q(('entity_type', ''), _negated=True), name='core_sync_operation_entity_type_not_empty'), models.CheckConstraint(condition=models.Q(('entity_client_id', ''), _negated=True), name='core_sync_operation_entity_client_id_not_empty'), models.CheckConstraint(condition=models.Q(('payload_hash', ''), _negated=True), name='core_sync_operation_payload_hash_not_empty')],
            },
        ),
    ]
