# Generated by Django 6.0.8 on 2026-08-07 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def provision_identity_records(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    UserPreference = apps.get_model("accounts", "UserPreference")
    UserProfile = apps.get_model("accounts", "UserProfile")

    for user in User.objects.all().iterator():
        UserProfile.objects.get_or_create(user=user)
        UserPreference.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('weight_unit', models.CharField(choices=[('kg', 'Quilogramas'), ('lb', 'Libras')], default='kg', max_length=8)),
                ('distance_unit', models.CharField(choices=[('m', 'Metros'), ('km', 'Quilômetros'), ('mi', 'Milhas')], default='m', max_length=8)),
                ('appearance', models.CharField(choices=[('system', 'Sistema'), ('light', 'Claro'), ('dark', 'Escuro')], default='system', max_length=16)),
                ('rest_timer_sound_enabled', models.BooleanField(default=True)),
                ('rest_timer_vibration_enabled', models.BooleanField(default=True)),
                ('workout_reminders_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('training_goal', models.CharField(blank=True, choices=[('strength', 'Força'), ('hypertrophy', 'Hipertrofia'), ('endurance', 'Resistência'), ('general_fitness', 'Condicionamento geral')], max_length=32)),
                ('onboarding_status', models.CharField(choices=[('profile', 'Perfil'), ('training_goal', 'Objetivo'), ('physical_info', 'Informações físicas'), ('plan_setup', 'Configuração do plano'), ('completed', 'Completo')], default='profile', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('height_cm__isnull', True), ('height_cm__gt', 0), _connector='OR'), name='accounts_userprofile_height_positive'), models.CheckConstraint(condition=models.Q(('current_weight_kg__isnull', True), ('current_weight_kg__gt', 0), _connector='OR'), name='accounts_userprofile_weight_positive')],
            },
        ),
        migrations.RunPython(provision_identity_records, migrations.RunPython.noop),
    ]
