/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as ProgressExerciseRouteImport } from './routes/progress/exercise'
import { Route as ProgressLevelsRouteImport } from './routes/progress/levels'
import { Route as ProgressMeasurementsRouteImport } from './routes/progress/measurements'
import { Route as ProgressRecoveryRouteImport } from './routes/progress/recovery'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as WorkoutActiveRouteImport } from './routes/workout/active'
import { Route as WorkoutSummaryRouteImport } from './routes/workout/summary'
import { Route as ProgressHistoryIndexRouteImport } from './routes/progress/history.index'
import { Route as ProgressHistoryIdRouteImport } from './routes/progress/history.$id'
import { Route as ResetPasswordUidTokenRouteImport } from './routes/reset-password.$uid.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressExerciseRoute = ProgressExerciseRouteImport.update({
  id: '/progress/exercise',
  path: '/progress/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressLevelsRoute = ProgressLevelsRouteImport.update({
  id: '/progress/levels',
  path: '/progress/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressMeasurementsRoute = ProgressMeasurementsRouteImport.update({
  id: '/progress/measurements',
  path: '/progress/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRecoveryRoute = ProgressRecoveryRouteImport.update({
  id: '/progress/recovery',
  path: '/progress/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutActiveRoute = WorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSummaryRoute = WorkoutSummaryRouteImport.update({
  id: '/workout/summary',
  path: '/workout/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressHistoryIndexRoute = ProgressHistoryIndexRouteImport.update({
  id: '/progress/history/',
  path: '/progress/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressHistoryIdRoute = ProgressHistoryIdRouteImport.update({
  id: '/progress/history/$id',
  path: '/progress/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordUidTokenRoute = ResetPasswordUidTokenRouteImport.update({
  id: '/reset-password/$uid/$token',
  path: '/reset-password/$uid/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/progress/exercise': typeof ProgressExerciseRoute
  '/progress/levels': typeof ProgressLevelsRoute
  '/progress/measurements': typeof ProgressMeasurementsRoute
  '/progress/recovery': typeof ProgressRecoveryRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/progress/': typeof ProgressIndexRoute
  '/workout/': typeof WorkoutIndexRoute
  '/progress/history/$id': typeof ProgressHistoryIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
  '/progress/history/': typeof ProgressHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/progress/exercise': typeof ProgressExerciseRoute
  '/progress/levels': typeof ProgressLevelsRoute
  '/progress/measurements': typeof ProgressMeasurementsRoute
  '/progress/recovery': typeof ProgressRecoveryRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/progress': typeof ProgressIndexRoute
  '/workout': typeof WorkoutIndexRoute
  '/progress/history/$id': typeof ProgressHistoryIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
  '/progress/history': typeof ProgressHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/progress/exercise': typeof ProgressExerciseRoute
  '/progress/levels': typeof ProgressLevelsRoute
  '/progress/measurements': typeof ProgressMeasurementsRoute
  '/progress/recovery': typeof ProgressRecoveryRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/progress/': typeof ProgressIndexRoute
  '/workout/': typeof WorkoutIndexRoute
  '/progress/history/$id': typeof ProgressHistoryIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
  '/progress/history/': typeof ProgressHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/onboarding'
    | '/plan'
    | '/signin'
    | '/signup'
    | '/progress/exercise'
    | '/progress/levels'
    | '/progress/measurements'
    | '/progress/recovery'
    | '/workout/active'
    | '/workout/summary'
    | '/progress/'
    | '/workout/'
    | '/progress/history/$id'
    | '/reset-password/$uid/$token'
    | '/progress/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/onboarding'
    | '/plan'
    | '/signin'
    | '/signup'
    | '/progress/exercise'
    | '/progress/levels'
    | '/progress/measurements'
    | '/progress/recovery'
    | '/workout/active'
    | '/workout/summary'
    | '/progress'
    | '/workout'
    | '/progress/history/$id'
    | '/reset-password/$uid/$token'
    | '/progress/history'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/forgot-password'
    | '/onboarding'
    | '/plan'
    | '/signin'
    | '/signup'
    | '/progress/exercise'
    | '/progress/levels'
    | '/progress/measurements'
    | '/progress/recovery'
    | '/workout/active'
    | '/workout/summary'
    | '/progress/'
    | '/workout/'
    | '/progress/history/$id'
    | '/reset-password/$uid/$token'
    | '/progress/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ProgressExerciseRoute: typeof ProgressExerciseRoute
  ProgressLevelsRoute: typeof ProgressLevelsRoute
  ProgressMeasurementsRoute: typeof ProgressMeasurementsRoute
  ProgressRecoveryRoute: typeof ProgressRecoveryRoute
  WorkoutActiveRoute: typeof WorkoutActiveRoute
  WorkoutSummaryRoute: typeof WorkoutSummaryRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
  ProgressHistoryIdRoute: typeof ProgressHistoryIdRoute
  ResetPasswordUidTokenRoute: typeof ResetPasswordUidTokenRoute
  ProgressHistoryIndexRoute: typeof ProgressHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/exercise': {
      id: '/progress/exercise'
      path: '/progress/exercise'
      fullPath: '/progress/exercise'
      preLoaderRoute: typeof ProgressExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/levels': {
      id: '/progress/levels'
      path: '/progress/levels'
      fullPath: '/progress/levels'
      preLoaderRoute: typeof ProgressLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/measurements': {
      id: '/progress/measurements'
      path: '/progress/measurements'
      fullPath: '/progress/measurements'
      preLoaderRoute: typeof ProgressMeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/recovery': {
      id: '/progress/recovery'
      path: '/progress/recovery'
      fullPath: '/progress/recovery'
      preLoaderRoute: typeof ProgressRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/active': {
      id: '/workout/active'
      path: '/workout/active'
      fullPath: '/workout/active'
      preLoaderRoute: typeof WorkoutActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/summary': {
      id: '/workout/summary'
      path: '/workout/summary'
      fullPath: '/workout/summary'
      preLoaderRoute: typeof WorkoutSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/history/': {
      id: '/progress/history/'
      path: '/progress/history'
      fullPath: '/progress/history/'
      preLoaderRoute: typeof ProgressHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/history/$id': {
      id: '/progress/history/$id'
      path: '/progress/history/$id'
      fullPath: '/progress/history/$id'
      preLoaderRoute: typeof ProgressHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$uid/$token': {
      id: '/reset-password/$uid/$token'
      path: '/reset-password/$uid/$token'
      fullPath: '/reset-password/$uid/$token'
      preLoaderRoute: typeof ResetPasswordUidTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ProgressExerciseRoute: ProgressExerciseRoute,
  ProgressLevelsRoute: ProgressLevelsRoute,
  ProgressMeasurementsRoute: ProgressMeasurementsRoute,
  ProgressRecoveryRoute: ProgressRecoveryRoute,
  WorkoutActiveRoute: WorkoutActiveRoute,
  WorkoutSummaryRoute: WorkoutSummaryRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
  ProgressHistoryIdRoute: ProgressHistoryIdRoute,
  ResetPasswordUidTokenRoute: ResetPasswordUidTokenRoute,
  ProgressHistoryIndexRoute: ProgressHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
