/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as ProgressExerciseRouteImport } from './routes/progress/exercise'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as WorkoutActiveRouteImport } from './routes/workout/active'
import { Route as WorkoutSummaryRouteImport } from './routes/workout/summary'
import { Route as ProgressHistoryIndexRouteImport } from './routes/progress/history.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressExerciseRoute = ProgressExerciseRouteImport.update({
  id: '/progress/exercise',
  path: '/progress/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutActiveRoute = WorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSummaryRoute = WorkoutSummaryRouteImport.update({
  id: '/workout/summary',
  path: '/workout/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressHistoryIndexRoute = ProgressHistoryIndexRouteImport.update({
  id: '/progress/history/',
  path: '/progress/history/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/signin': typeof SigninRoute
  '/progress/exercise': typeof ProgressExerciseRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/progress/': typeof ProgressIndexRoute
  '/workout/': typeof WorkoutIndexRoute
  '/progress/history/': typeof ProgressHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/signin': typeof SigninRoute
  '/progress/exercise': typeof ProgressExerciseRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/progress': typeof ProgressIndexRoute
  '/workout': typeof WorkoutIndexRoute
  '/progress/history': typeof ProgressHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/signin': typeof SigninRoute
  '/progress/exercise': typeof ProgressExerciseRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/progress/': typeof ProgressIndexRoute
  '/workout/': typeof WorkoutIndexRoute
  '/progress/history/': typeof ProgressHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/plan'
    | '/signin'
    | '/progress/exercise'
    | '/workout/active'
    | '/workout/summary'
    | '/progress/'
    | '/workout/'
    | '/progress/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/plan'
    | '/signin'
    | '/progress/exercise'
    | '/workout/active'
    | '/workout/summary'
    | '/progress'
    | '/workout'
    | '/progress/history'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/plan'
    | '/signin'
    | '/progress/exercise'
    | '/workout/active'
    | '/workout/summary'
    | '/progress/'
    | '/workout/'
    | '/progress/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  SigninRoute: typeof SigninRoute
  ProgressExerciseRoute: typeof ProgressExerciseRoute
  WorkoutActiveRoute: typeof WorkoutActiveRoute
  WorkoutSummaryRoute: typeof WorkoutSummaryRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
  ProgressHistoryIndexRoute: typeof ProgressHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/exercise': {
      id: '/progress/exercise'
      path: '/progress/exercise'
      fullPath: '/progress/exercise'
      preLoaderRoute: typeof ProgressExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/active': {
      id: '/workout/active'
      path: '/workout/active'
      fullPath: '/workout/active'
      preLoaderRoute: typeof WorkoutActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/summary': {
      id: '/workout/summary'
      path: '/workout/summary'
      fullPath: '/workout/summary'
      preLoaderRoute: typeof WorkoutSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/history/': {
      id: '/progress/history/'
      path: '/progress/history'
      fullPath: '/progress/history/'
      preLoaderRoute: typeof ProgressHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  SigninRoute: SigninRoute,
  ProgressExerciseRoute: ProgressExerciseRoute,
  WorkoutActiveRoute: WorkoutActiveRoute,
  WorkoutSummaryRoute: WorkoutSummaryRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
  ProgressHistoryIndexRoute: ProgressHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
