# Generated by Django 6.0.8 on 2026-08-08 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('primary_metric', models.CharField(choices=[('repetitions', 'Repetições'), ('weight_repetitions', 'Peso e repetições'), ('duration', 'Duração'), ('distance', 'Distância'), ('distance_duration', 'Distância e duração')], max_length=32)),
                ('default_rest_seconds', models.PositiveIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='training_exercise_name_not_empty'), models.CheckConstraint(condition=models.Q(('default_rest_seconds__gte', 0)), name='training_exercise_default_rest_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('source_type', models.CharField(choices=[('admin', 'Administração'), ('spreadsheet_import', 'Importação de planilha'), ('system', 'Sistema')], default='admin', max_length=32)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ('user', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PlanWorkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField()),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='training.trainingplan')),
            ],
            options={
                'db_table': 'plan_workouts',
                'ordering': ('training_plan', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('target_sets', models.PositiveIntegerField()),
                ('target_repetitions_min', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repetitions_max', models.PositiveIntegerField(blank=True, null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('target_distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('technical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_prescriptions', to='training.exercise')),
                ('plan_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_prescriptions', to='training.planworkout')),
            ],
            options={
                'db_table': 'workout_exercises',
                'ordering': ('plan_workout', 'sequence'),
            },
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['user', 'status'], name='training_plan_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingplan',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='training_plan_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='trainingplan',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='training_plan_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='trainingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='training_one_active_plan_per_user'),
        ),
        migrations.AddIndex(
            model_name='planworkout',
            index=models.Index(fields=['training_plan', 'sequence'], name='trn_workout_plan_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='planworkout',
            constraint=models.UniqueConstraint(fields=('training_plan', 'sequence'), name='training_plan_workout_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='planworkout',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='training_plan_workout_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='planworkout',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='training_plan_workout_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='planworkout',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_minutes__isnull', True), ('estimated_duration_minutes__gt', 0), _connector='OR'), name='training_plan_workout_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['plan_workout', 'sequence'], name='trn_exercise_workout_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('plan_workout', 'sequence'), name='training_workout_exercise_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='training_workout_exercise_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('target_sets__gt', 0)), name='training_workout_exercise_sets_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('target_repetitions_min__isnull', True), ('target_repetitions_max__isnull', True), ('target_repetitions_max__gte', models.F('target_repetitions_min')), _connector='OR'), name='training_workout_exercise_reps_ordered'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('target_weight_kg__isnull', True), ('target_weight_kg__gte', 0), _connector='OR'), name='training_workout_exercise_weight_non_negative'),
        ),
    ]
