# Generated by Django 6.0.8 on 2026-08-08 11:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('completed', 'Concluído'), ('skipped', 'Pulado')], default='pending', max_length=16)),
                ('exercise_name_snapshot', models.CharField(max_length=160)),
                ('exercise_instructions_snapshot', models.TextField(blank=True)),
                ('technical_notes_snapshot', models.TextField(blank=True)),
                ('primary_metric_snapshot', models.CharField(choices=[('repetitions', 'Repetições'), ('weight_repetitions', 'Peso e repetições'), ('duration', 'Duração'), ('distance', 'Distância'), ('distance_duration', 'Distância e duração')], max_length=32)),
                ('target_sets_snapshot', models.PositiveIntegerField()),
                ('target_repetitions_min_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repetitions_max_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('target_weight_kg_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_duration_seconds_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('target_distance_meters_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_snapshots', to='training.exercise')),
                ('source_workout_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_snapshots', to='training.workoutexercise')),
            ],
            options={
                'db_table': 'session_exercises',
                'ordering': ('workout_session', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_generated_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=16)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('workout_name_snapshot', models.CharField(max_length=160)),
                ('workout_description_snapshot', models.TextField(blank=True)),
                ('source_revision', models.CharField(blank=True, max_length=64)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('conflict', 'Conflito'), ('failed', 'Falhou')], default='synced', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='training.planworkout')),
                ('training_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='training.trainingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_sessions',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='training.sessionexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to=settings.AUTH_USER_MODEL)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='training.workoutsession')),
            ],
            options={
                'db_table': 'session_notes',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_snapshots', to='training.workoutsession'),
        ),
        migrations.CreateModel(
            name='CompletedSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_generated_id', models.UUIDField(default=uuid.uuid4)),
                ('set_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Concluído'), ('skipped', 'Pulado')], default='completed', max_length=16)),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('perceived_effort', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('conflict', 'Conflito'), ('failed', 'Falhou')], default='synced', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='training.sessionexercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='training.workoutsession')),
            ],
            options={
                'db_table': 'completed_sets',
                'ordering': ('session_exercise', 'set_number'),
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'status'], name='trn_session_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-started_at'], name='trn_session_user_start_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-completed_at'], name='trn_session_user_done_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'paused'))), fields=('user',), name='training_one_open_workout_session_per_user'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(fields=('user', 'client_generated_id'), name='training_workout_session_client_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__gte', 0), _connector='OR'), name='training_workout_session_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='training_workout_session_completed_at_required'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='training_workout_session_cancelled_at_required'),
        ),
        migrations.AddConstraint(
            model_name='sessionnote',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='training_session_note_content_not_empty'),
        ),
        migrations.AddIndex(
            model_name='sessionexercise',
            index=models.Index(fields=['workout_session', 'sequence'], name='trn_session_exercise_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionexercise',
            constraint=models.UniqueConstraint(fields=('workout_session', 'sequence'), name='training_session_exercise_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='sessionexercise',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='training_session_exercise_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='sessionexercise',
            constraint=models.CheckConstraint(condition=models.Q(('target_sets_snapshot__gt', 0)), name='training_session_exercise_sets_positive'),
        ),
        migrations.AddIndex(
            model_name='completedset',
            index=models.Index(fields=['workout_session', 'completed_at'], name='trn_set_session_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='completedset',
            constraint=models.UniqueConstraint(fields=('workout_session', 'client_generated_id'), name='training_completed_set_client_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='completedset',
            constraint=models.UniqueConstraint(fields=('session_exercise', 'set_number'), name='training_completed_set_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='completedset',
            constraint=models.CheckConstraint(condition=models.Q(('set_number__gt', 0)), name='training_completed_set_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='completedset',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'skipped'), ('repetitions__isnull', False), ('weight_kg__isnull', False), ('duration_seconds__isnull', False), ('distance_meters__isnull', False), _connector='OR'), name='training_completed_set_meaningful_data'),
        ),
        migrations.AddConstraint(
            model_name='completedset',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), ('weight_kg__gte', 0), _connector='OR'), name='training_completed_set_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='completedset',
            constraint=models.CheckConstraint(condition=models.Q(('perceived_effort__isnull', True), models.Q(('perceived_effort__gte', 1), ('perceived_effort__lte', 10)), _connector='OR'), name='training_completed_set_effort_range'),
        ),
    ]
