# Generated by Django 6.0.8 on 2026-08-08 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0002_sessionexercise_workoutsession_sessionnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal')], default='daily', max_length=16)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_definitions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_generated_id', models.UUIDField(default=uuid.uuid4)),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Concluído'), ('partial', 'Parcial'), ('missed', 'Não feito'), ('not_applicable', 'Não aplicável')], max_length=24)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('conflict', 'Conflito'), ('failed', 'Falhou')], default='synced', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='progress.habitdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_entries',
                'ordering': ('-entry_date',),
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('maximum_weight', 'Maior peso'), ('maximum_repetitions', 'Mais repetições'), ('maximum_distance', 'Maior distância'), ('longest_duration', 'Maior duração'), ('highest_volume', 'Maior volume')], max_length=32)),
                ('value_numeric', models.DecimalField(decimal_places=2, max_digits=12)),
                ('secondary_value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('achieved_at', models.DateTimeField()),
                ('calculation_version', models.CharField(default='v1', max_length=32)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_records', to='training.completedset')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_records', to='training.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_records',
                'ordering': ('-achieved_at',),
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_generated_id', models.UUIDField(default=uuid.uuid4)),
                ('measurement_date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hips_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('left_arm_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('right_arm_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('left_thigh_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('right_thigh_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('conflict', 'Conflito'), ('failed', 'Falhou')], default='synced', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'body_measurements',
                'ordering': ('-measurement_date',),
                'indexes': [models.Index(fields=['user', 'measurement_date'], name='prog_measure_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'measurement_date'), name='progress_body_measurement_user_date_unique'), models.UniqueConstraint(fields=('user', 'client_generated_id'), name='progress_body_measurement_client_id_unique'), models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), ('weight_kg__gte', 0), _connector='OR'), name='progress_body_weight_non_negative'), models.CheckConstraint(condition=models.Q(('body_fat_percentage__isnull', True), models.Q(('body_fat_percentage__gte', 0), ('body_fat_percentage__lte', 100)), _connector='OR'), name='progress_body_fat_range')],
            },
        ),
        migrations.CreateModel(
            name='DailyRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_generated_id', models.UUIDField(default=uuid.uuid4)),
                ('recovery_date', models.DateField()),
                ('sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('hydration_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('cardio_completed', models.BooleanField(default=False)),
                ('recovery_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('conflict', 'Conflito'), ('failed', 'Falhou')], default='synced', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recovery_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_recovery',
                'ordering': ('-recovery_date',),
                'indexes': [models.Index(fields=['user', 'recovery_date'], name='prog_recovery_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recovery_date'), name='progress_daily_recovery_user_date_unique'), models.UniqueConstraint(fields=('user', 'client_generated_id'), name='progress_daily_recovery_client_id_unique'), models.CheckConstraint(condition=models.Q(('recovery_score__isnull', True), models.Q(('recovery_score__gte', 0), ('recovery_score__lte', 100)), _connector='OR'), name='progress_daily_recovery_score_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='habitdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='progress_habit_definition_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='habitdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('target_value__isnull', True), ('target_value__gte', 0), _connector='OR'), name='progress_habit_target_non_negative'),
        ),
        migrations.AddIndex(
            model_name='habitentry',
            index=models.Index(fields=['user', 'entry_date'], name='progress_habit_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.UniqueConstraint(fields=('habit_definition', 'entry_date'), name='progress_habit_entry_definition_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.UniqueConstraint(fields=('user', 'client_generated_id'), name='progress_habit_entry_client_id_unique'),
        ),
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['user', 'exercise', 'record_type', 'is_current'], name='progress_record_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='personalrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user', 'exercise', 'record_type'), name='progress_one_current_record_per_type'),
        ),
        migrations.AddConstraint(
            model_name='personalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('value_numeric__gte', 0)), name='progress_personal_record_value_non_negative'),
        ),
    ]
