# Generated by Django 6.0.8 on 2026-08-08 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('training', 'Treino'), ('consistency', 'Consistência'), ('progress', 'Progresso'), ('recovery', 'Recuperação'), ('history', 'Histórico'), ('return', 'Retorno')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExperienceLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('workout_completion', 'Treino concluído'), ('exercise_completion', 'Exercício concluído'), ('completed_set', 'Série concluída'), ('personal_record', 'Recorde pessoal'), ('recovery_registration', 'Recuperação registrada'), ('habit_completion', 'Hábito concluído'), ('measurement_snapshot', 'Medição registrada'), ('admin_adjustment', 'Ajuste administrativo')], max_length=40)),
                ('source_entity_type', models.CharField(max_length=80)),
                ('source_entity_id', models.UUIDField()),
                ('experience_delta', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('calculation_version', models.CharField(default='xp_v1', max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experience_ledger',
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='progress_xp_user_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'source_entity_type', 'source_entity_id'), name='progress_experience_source_unique'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='progress_experience_reason_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_entity_type', models.CharField(max_length=80)),
                ('source_entity_id', models.UUIDField()),
                ('earned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_by', to='progress.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ('-earned_at',),
                'indexes': [models.Index(fields=['user', '-earned_at'], name='prog_achievement_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='progress_user_achievement_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserProgression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_experience', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('performance_score', models.PositiveSmallIntegerField(default=0)),
                ('consistency_score', models.PositiveSmallIntegerField(default=0)),
                ('recovery_score', models.PositiveSmallIntegerField(default=0)),
                ('calculation_version', models.CharField(default='level_v1', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_progression',
                'constraints': [models.CheckConstraint(condition=models.Q(('current_level__gte', 1)), name='progress_user_level_positive'), models.CheckConstraint(condition=models.Q(('performance_score__gte', 0), ('performance_score__lte', 100)), name='progress_performance_score_range'), models.CheckConstraint(condition=models.Q(('consistency_score__gte', 0), ('consistency_score__lte', 100)), name='progress_consistency_score_range'), models.CheckConstraint(condition=models.Q(('recovery_score__gte', 0), ('recovery_score__lte', 100)), name='progress_recovery_score_range')],
            },
        ),
    ]
